# Generated by Django 5.2.17 on 2026-09-15 10:22

import django.db.models.deletion
import modules.materials.models
from django.db import migrations, models


def transfer_attachments(apps, schema_editor):
    Task = apps.get_model("materials", "Task")
    Attachment = apps.get_model("materials", "TaskAttachment")
    alias = schema_editor.connection.alias
    for task in Task.objects.using(alias).exclude(attachment="").iterator():
        Attachment.objects.using(alias).create(task_id=task.pk, file=task.attachment.name)


def restore_single_attachments(apps, schema_editor):
    Task = apps.get_model("materials", "Task")
    Attachment = apps.get_model("materials", "TaskAttachment")
    alias = schema_editor.connection.alias
    from django.db.models import Count
    if Attachment.objects.using(alias).values("task_id").annotate(total=Count("pk")).filter(total__gt=1).exists():
        raise RuntimeError("Нельзя откатить миграцию: у задания несколько вложений.")
    for attachment in Attachment.objects.using(alias).iterator():
        Task.objects.using(alias).filter(pk=attachment.task_id).update(attachment=attachment.file.name)


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=modules.materials.models.attachment_path, verbose_name='Файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(transfer_attachments, restore_single_attachments),
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
    ]
