# Generated by Django 5.2.17 on 2026-09-20 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_step', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('next_review_date', models.DateField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='users.studenttopic')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('interval_step__gte', 0), ('interval_step__lte', 5)), name='progress_step_0_to_5')],
            },
        ),
    ]
