# Generated by Django 5.2.17 on 2026-09-25 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetitions', '0002_existing_assignments'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topicprogress',
            name='progress_step_0_to_5',
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='interval_step',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.CheckConstraint(condition=models.Q(('interval_step__gte', 0), ('interval_step__lte', 6)), name='progress_step_0_to_6'),
        ),
    ]
