# Generated by Django 5.2.17 on 2026-09-17 18:21

import django.core.validators
import django.db.models.deletion
import modules.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_remove_task_attachment_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='Username')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя Telegram')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия Telegram')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя для учителя')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-registered_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=modules.users.models.invitation_token, editable=False, max_length=64, unique=True, verbose_name='Токен')),
                ('note', models.TextField(blank=True, verbose_name='Заметка учителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата использования')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.course', verbose_name='Курс')),
                ('student', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пройдена и включена')),
                ('activated_at', models.DateTimeField(verbose_name='Последнее включение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_assignments', to='users.student', verbose_name='Ученик')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Пройденная тема',
                'verbose_name_plural': 'Пройденные темы',
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('telegram_id__gt', 0)), name='student_positive_telegram_id'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', True), ('used_at__isnull', True)), models.Q(('is_revoked', False), ('student__isnull', False), ('used_at__isnull', False)), _connector='OR'), name='invitation_consistent_usage'),
        ),
        migrations.AddConstraint(
            model_name='studenttopic',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='unique_student_topic'),
        ),
    ]
