# Generated by Django 5.2.17 on 2026-10-05 18:09

import django.db.models.deletion
from django.db import migrations, models


def protect_reverse(apps, schema_editor):
    for name in ('IncomingEvent', 'OutgoingMessage', 'QuestionDelivery'):
        if apps.get_model('delivery', name).objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError('Delivery history exists; restore a coordinated backup instead of reversing stage 7.')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_sessions', '0003_daily_queue'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=12)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('last_message_id', models.BigIntegerField(null=True)),
                ('operation', models.CharField(max_length=120)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='study_sessions.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.PositiveBigIntegerField()),
                ('update_id', models.BigIntegerField()),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(null=True)),
                ('state', models.CharField(default='processing', max_length=12)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_sessions.attempt')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_sessions.studysession')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bot_id', 'update_id'), name='unique_bot_update')],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.PositiveBigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('operation', models.CharField(max_length=120)),
                ('part', models.PositiveIntegerField()),
                ('kind', models.CharField(default='text', max_length=12)),
                ('is_question', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('retry', 'Повтор'), ('sent', 'Отправлено'), ('failed', 'Окончательная ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('error', models.CharField(blank=True, max_length=32)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_sessions.attempt')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='study_sessions.studysession')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['bot_id', 'chat_id', 'state'], name='delivery_ou_bot_id_49124e_idx'), models.Index(fields=['state', 'next_attempt_at'], name='delivery_ou_state_dec028_idx')],
                'constraints': [models.UniqueConstraint(fields=('bot_id', 'operation', 'part'), name='unique_outgoing_part')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_reverse),
    ]
