# Generated by Django 5.2.17 on 2026-10-06 13:12

import django.utils.timezone
from django.db import migrations, models


def protect_history(apps, schema_editor):
    if apps.get_model('delivery', 'OutgoingMessage').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Delivery history exists; restore a compatible backup for rollback')


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Refuse before dropping created_at: a failed full rollback must leave
        # the latest migration applied and the running model usable.
        migrations.RunPython(migrations.RunPython.noop, protect_history),
    ]
