# Generated by Django 5.2.17 on 2026-09-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_remove_task_attachment_taskattachment'),
        ('users', '0001_initial'),
        ('repetitions', '0003_six_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('state', models.CharField(default='open', max_length=10)),
                ('skipped', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='open', max_length=10)),
                ('response', models.TextField(null=True)),
                ('question', models.TextField()),
                ('reference', models.TextField()),
                ('topic_title', models.CharField(max_length=200)),
                ('attachments', models.JSONField(default=list)),
                ('task_order', models.PositiveIntegerField()),
                ('cancellation_seen', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studenttopic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.task')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='study_sessions.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_order', models.PositiveIntegerField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.studenttopic')),
                ('last_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('student',), name='one_open_session_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state', 'open')), models.Q(('finished_at__isnull', False), ('state', 'finished')), _connector='OR'), name='session_consistent_state'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('student',), name='one_open_attempt_per_student'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('session', 'assignment'), name='one_topic_per_session'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('response__isnull', True), ('status', 'open')), models.Q(('finished_at__isnull', False), ('response__isnull', True), ('status', 'cancelled')), models.Q(('finished_at__isnull', False), ('response__isnull', False), ('status__in', ['correct', 'incorrect'])), _connector='OR'), name='attempt_consistent_state'),
        ),
    ]
